  <?php echo $this->flashSession->output(); 
 
  $username='';
  $password='';
  $rememberMe='';
 
  if($this->cookies->has("username") && $this->cookies->has("password") )
  {
      $username=$this->cookies->get("username");
      $password=$this->cookies->get("password");
      $rememberMe='checked';
  }
?>
<!DOCTYPE html>
<html lang="en">
<head>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="<?php echo $this->url->getBaseUri().'/public/css/ihatethiswork.css' ?>" rel="stylesheet">
</head>

<!--
    you can substitue the span of reauth email for a input with the email and
    include the remember me checkbox
    -->
<body>
    <div class="container">
        <div class="card card-container">
            <!-- <img class="profile-img-card" src="//lh3.googleusercontent.com/-6V8xOA6M7BA/AAAAAAAAAAI/AAAAAAAAAAA/rzlHcD0KYwo/photo.jpg?sz=120" alt="" /> -->
            <div class="wrapper">
            <form action="" method="post" name="Login_Form" class="form-signin">
                <h3 class="form-signin-heading">Welcome Back! Please Sign In</h3>
			    <hr class="colorgraph"><br>
                <span id="reauth-email" class="reauth-email"></span>
                <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Enter email" required autofocus value="<?php if(isset($username))echo $username; ?>">
                <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required value="<?php if(isset($password))echo $password; ?>">
                <div id="remember" class="checkbox">
                    <label>
                    <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>> Remember me
                    </label>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
                <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-lg btn-primary btn-block">Back</a>
            </form><!-- /form -->
        </div><!-- /card-container -->
        </div>
    </div><!-- /container -->
    
    <script src="<?php echo $this->url->getBaseUri().'/public/js/ihatethiswork.js' ?>"></script>
</body>

<!-- <form action="" method="post">
  
    <div class="form-group">
      <label>Email address</label>
      <input type="email" name="email" class="form-control" id="email" placeholder="Enter email" value="<?php if(isset($username))echo $username; ?>" required>
    </div>
    <div class="form-group">
      <label>Password</label>
      <input type="password" name="password" class="form-control" id="password" placeholder="Password" value="<?php if(isset($password))echo $password; ?>" required>
     
    </div>
    <div class="form-check">
      <input type="checkbox" name="rememberMe" class="form-check-input" id="rememberMe" value="1" <?php echo $rememberMe;?>>
 
      <label class="form-check-label" for="rememberMe">Remember me</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
   
    <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
   
  </form> -->
