<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Phalcon PHP Framework Login</title>    
    <?php echo $this->assets->outputCss('styleslogin'); ?>
    <?php echo $this->assets->outputJs('scripts'); ?> 
    <link rel="stylesheet" type="text/css" href="css/login.css">
  </head>
  <body>
<div class="container"><?php echo $this->getContent(); ?></div>
 
</body>
</html>
